server:
  port: 8081

spring:
  application:
    name: user-center

  datasource:
    url: jdbc:mysql://192.144.238.26:3306/user-center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1226Sg@
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false


mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lvpb.model.domain


knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    show-extensions: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-flat-param-object: false
  group-configs:
    - group: '用户中心'
      paths-to-match: '/**'
      packages-to-scan: com.lvpb.controller
